Gemfile:
  optional:
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
.travis.yml:
  secure: "a+OXt7VqbLVBAbCoKljk+xrZbXNjfdknVtSKU0s8LaIpEjIgP9UcBdOm47EGHOsn/mZixXX/R52vNk6XGgC6eysR2VaZZHHtSPCzL20pSwoQpGSmmHlwHCSHYp4f6B66m2KnOxsEFDv4IrLjgKc3Q+y15Kwj4OVW6sW/XfqKWpo="
